name: geog0133_env

dependencies:
    - python>=3.6
    - jupyter
    - tornado<6
    - gdal>=2.4.1
    - tqdm
    - libgdal>=2.4.1
    - numpy
    - scipy
    - matplotlib
    - ipywidgets
    - ipyleaflet
    - pandas
    - jupyter_contrib_nbextensions
    - widgetsnbextension
